/// @file
/// ABM epidemic model with enviroment  - using template for AGENT BASE MODEL in 2D discrete geometry.
//  PL: Agentowy model epidemii ze środowiskiem (z wykorzystaniem szablonu MODELU AGENTOWEGO w dyskretnej geometrii 2D)
/// @author implemented by Wojciech Borkowski
/// @date 2024 (this automaticly generated file was manually modified!)
//*//////////////////////////////////////////////////////////////////////////////////////////////////////////////////


import processing.core.*; 
import processing.data.*; 
import processing.event.*; 
import processing.opengl.*; 

import com.hamoid.*; 

import java.util.HashMap; 
import java.util.ArrayList; 
import java.io.File; 
import java.io.BufferedReader; 
import java.io.PrintWriter; 
import java.io.InputStream; 
import java.io.OutputStream; 
import java.io.IOException; 

/// @brief Main class is generated by Processing and has same name as whole application.
/// @details 
/// 	PL: 
///     Generalny pomysł jest taki, że mamy miasto podzielone drogami, złożone z obszarów mieszkalnych (jasne) i miejsc pracy (szare).
/// 	Ci sami agenci na zmianę są w domu lub w pracy, i wszędzie mogą zarazić się przez kontakt.
/// 	Stąd jeden krok symulacji to pół dnia - parzyste kroki w pracy, nieparzyste w domu, chyba że agent nie ma pracy.
///
/// 	Właściwości danego wirusa są opisane parametrami symulacji.
/// 	Właściwością agentów poza rozlosowaną z rozkładu dwumianowego "immunity" jest tylko wiedza o miejscu zamieszkania i miejscu pracy.
public class cityOfplague extends PApplet {

// PARAMETRY MODELU
//*////////////////
String modelName="ABMcity_of_plague"; ///< NAZWA modelu.
int RANDSEED=-1033;                   ///< Ziarno liczb losowych. Jak 0 to będzie pobrane z aktualnego czasu.

int side=300;                         ///< DŁUGOŚĆ BOKU ŚWIATA - PIONOWEGO. Wymiar poziomy jest x 2.
float density=0.66f;                  ///< Gęstość zaludnienia na "terenach mieszkalnych".

//final float PTransfer=???;          //   Prawdopodobieństwo zarażenia agenta w pojedynczej interakcji.
                                      //   teraz zależy już tylko od indywidualnej wartości `immunity`.
                              
// DOMYŚLNE WŁAŚCIWOŚCI ZARAZKA
//*////////////////////////////
final float  defPSLeav=0.90f;     ///< Domyślne prawdopodobieństwo, że danego DNIA chory agent nie będzie w stanie iść do pracy.                             
final float  defPDeath=0.15f;     ///< Domyślne średnie prawdopodobieństwo śmierci w danym kroku(!) choroby. Teraz krok to 12 godzin.
final int    defDuration=14;      ///< Domyślny czas trwania infekcji! W krokach symulacji. Teraz krok to 12 godzin!!! Czyli default to 7 dni.

// Właściwości nie związane z epidemią
//*////////////////////////////////////
final int    Nprob=10;            ///< Liczba prób szukania pracy w inicjalizacji. Jak się nie uda to agent cały czas siedzi w domu.
final float  dutifulness=0.900f;  ///< Jak często zdrowi agenci idą do pracy. Mogą pracować w domu lub mieć ograniczone wychodzenie.
final float  lockdownness=0.20f;  ///< Ale lockdown nigdy nie jest kompletny (RACZEJ?).
final int    lockdownStep=20;     ///< W którym kroku symulacji (2 kroki na dzień) wprowadzamy lockdown.
final int    protestStep=40;      ///< W którym króku pojawia się demonstracja uliczna.

// Stałe używane do określania stanu agentów   
//*/////////////////////////////////////////
final int Infected=1;                  ///< Stała oznaczająca zainfekowanie.
final int Recovered=0;                 ///< Stała oznaczająca WYLECZENIE.
final int HostDeath=Integer.MAX_VALUE; ///< ... todo: Ryzykowne nieco(?) bo w wirusie jest pole typu `float`.

World TheWorld=new World(side);        ///< INICJALIZACJA ŚWIATA. JEST KOŃCZONA W FUNKCJI `setup()`.

// STATYSTYKI LICZONE W TRAKCIE SYMULACJI
//*//////////////////////////////////////
int liveCount=0;                       ///< Ile żywych agentów.

int sumInfected=0;                     ///< Zachorowania.
int sumRecovered=0;                    ///< Wyzdrowienia.
int sumDeath=0;                        ///< Ci co umarli.

FloatList deaths=new FloatList();      ///< Historia zgonów. 
FloatList newcas=new FloatList();      ///< Historia nowych zachorowań.
FloatList  cured=new FloatList();      ///< Historia wyleczeń.

// PARAMETRY WIZUALIZACJI, STATYSTYKI ITP.
//*///////////////////////////////////////
int cwidth=2;                          ///< DŁUGOŚĆ BOKU KOMÓRKI W WIZUALIZACJI.
                                       ///< WARTOSC NADANA TU JEST TYLKO WSTĘPNA.
int STATUSHEIGH=150;                   ///< WYSOKOŚĆ PASKA STATUSU NA DOLE OKNA.
int STEPSperVIS=1;                     ///< JAK CZĘSTO URUCHAMIAMY WIZUALIZACJĘ.
int FRAMEFREQ=4;                       ///< ILE RAZY NA SEKUNDĘ URUCHAMIA SIĘ `draw()`.

boolean WITH_VIDEO=true;               ///< CZY CHCEMY ZAPIS DO PLIKU FILMOWEGO (wymagany modu… "RTMVideo.pde").
boolean simulationRun=true;            ///< FLAGA Start/Stop DZIAŁANIA SYMULACJI.

public void setup()
{
  // GRAFIKA
   // 1 or 2, expecially for "Retina" (HERE?)
    // NIESTETY TU MOGĄ BYĆ TYLKO WARTOŚCI PODANE LITERALNIE CZYLI "LITERAŁY"!!!
  pixelDensity(1); // 1 or 2, expecially for "Retina" (or HERE?)
  println("Width:",width,"Height:",height,"displayDensity:",displayDensity());
        // Znacząco przyśpiesza wizualizacje
  frameRate(FRAMEFREQ);
  background(255,255,200);
  strokeWeight(2);
  if(RANDSEED!=0)
      randomSeed(RANDSEED); // Zasianie generatora gdy chcemy mieć powtarzalny przebieg.
  
  // INICJALIZACJA MODELU I (ewentualnie) STATYSTYK
  initializeModel(TheWorld); // DOKONCZENIE INICJALIZACJI ŚWIATA
  //initializeStats();       // ODKOMENTOWAĆ JEŚLI UŻYWAMY STATYSTYK
  doStatistics(TheWorld);    // J.W.
  
  // OBLICZAMY WYMAGANY ROZMIAR OKNA DLA size() 
  println(modelName+": REQUIRED SIZE OF PAINTING AREA IS "
          +(cwidth*side*2)+"x"+(cwidth*side+STATUSHEIGH)); // Tu brakowało 2.
          
  cwidth=(height-STATUSHEIGH)/side; // DOPASOWUJEMY ROZMIAR KOMÓREK DO OKNA JAKIE JEST.
  
  // INICJALIZACJA ZAPISU FILMU  (jeśli używamy RTMVideo.pde)
  if(WITH_VIDEO) {initVideoExport(this,modelName+".mp4",FRAMEFREQ);}
  
  // INFORMACJE KONSOLOWE NA KONIEC FUNKCJI setup()
  println("CURRENT SIZE OF PAINTING AREA IS "+width+"x"+height); // -myMenu.bounds.height???
  visualizeModel(TheWorld); // PIERWSZA PO INICJALIZACJI WIZUALIZACJA ŚWIATA
  FirstVideoFrame();
  
  if(!simulationRun) // WYMAGA MODUŁU RTMEvents.pde
    println("PRESS 'r' or 'ESC' to start simulation");
  else
    println("PRESS 's' or 'ESC' to pause simulation");
  
  NextVideoFrame(); // PIERWSZA REALNA KLATKA FILMU (o ile używamy RTMVideo.pde)
}

public void draw()
{
  if(simulationRun)
  {
    modelStep(TheWorld);
    doStatistics(TheWorld); // ODKOMENTOWAĆ JEŚLI UŻYWAMY STATYSTYK
  }                         // Używa wewnętrznej flagi określajacej czy log został otwarty
  
  writeStatusLine();
  
  if(!simulationRun                   // When simulation was stopped only visualisation should work
  || StepCounter % STEPSperVIS == 0 ) // But when model is running, visualisation should be done from time to time
  {
    visualizeModel(TheWorld);
    NextVideoFrame();                 // FUNKCJA ZAPISU KLATKI FILMU. 
  }                                   // Używa wewnętrznej flagi określajacej czy film został otwarty

}

/// @brief Wypełnianie linii statusu.
public void writeStatusLine()                ///< GLOBAL!
{
  fill(0);rect(0,side*cwidth,width,STATUSHEIGH);fill(128);
  histogram(TheWorld.agents,0,height-16,STATUSHEIGH-16); // Histogram wg. odporności  
  
                                                                   // Albo historie trzech zmiennych dziennych 
  // Legenda                                                       // w swojej skali
  stroke(0,0,255);fill(0,0,200);text("nowi chorzy",300,height-16);    //- timeline(newcas,200,height,STATUSHEIGH-16,false);
  stroke(255,0,0);fill(200,0,0);text("nowi zmarli",300,height-32);    //- timeline(deaths,200,height,STATUSHEIGH-16,false);
  stroke(0,255,0);fill(0,200,0);text("nowo wyleczeni",300,height-48); //- timeline(cured, 200,height,STATUSHEIGH-16,false);
  
  // Historie trzech zmiennych we wspólnej skali
  stroke(0,0,255);fill(0,0,255);
  timeline(newcas,deaths,cured, 200,height,STATUSHEIGH-16,false,color(0,0,255),color(255,0,0),color(0,255,0));
  
  fill(128);noStroke(); // Miejce dla NAJWAŻNIEJSZYCH STATYSTYK
  textAlign(RIGHT, TOP);
  text("Żyją:"+liveCount+" Zachorowali:"+sumInfected+" Wyzdrowieli:"+sumRecovered+" Umarli:_____________",width,side*cwidth);
  fill(255,0,0);
  text(" "+sumDeath+" ",width,side*cwidth);
  
  if(simulationRun) 
    println("ST:"+(StepCounter/2.0f)+"\tZ\t"+sumInfected+"\t"+newcas.get(newcas.size()-1)
                             +"\tW\t"+sumRecovered+"\t"+cured.get(cured.size()-1)
                             +"\tU\t"+sumDeath+"\t"+deaths.get(deaths.size()-1)
                             +"\t Fps:\t"+ frameRate);
                             
  textAlign(LEFT, BOTTOM);fill(255);
  text("Day:"+(StepCounter/2.0f)+" "+(lockdownStep<StepCounter?"LOCKDOWN:"+((1.0f-lockdownness)*100)+"%":""),0,height); //Ale lockdown nigdy nie jest kompletny (RACZEJ?)
}

//*/////////////////////////////////////////////////////////////////////////////////////////
//  https://www.researchgate.net/profile/WOJCIECH_BORKOWSKI - from ABM MAIN TEMPLATE
//*/////////////////////////////////////////////////////////////////////////////////////////
/// Agent is a one of two central class of each ABM model.
/// (Agent jest jedną z dwóch klas centralnych dla każdego modelu ABM)
//*///////////////////////////////////////////////////////////////////

/// @brief Agent podatny na infekcję jakimś wirusem.
class Agent
{
  Virus infection;   //!< Jaki ewentualnie wirus aktualnie infekuje. 
  float immunity;    //!< Odporność agenta. Zamiast dawnego PTransfer!
  
  // Położenie komórek zamieszkania i pracy
  int   flatX;       //!< X miejsca zamieszkania.
  int   flatY;       //!< Y miejsca zamieszkania.
  int   workX;       //!< X miejsca pracy.
  int   workY;       //!< Y miejsca pracy.
  
  /// @brief Konstruktor agenta. Inicjuje atrybuty.
  Agent(int initX,int initY) 
  {
    infection=null;
    flatX=workX=initX;
    flatY=workY=initY; //"workX|Y" mоże zostać sensowniej przypisane później
    immunity=( random(1.0f)+random(1.0f)+random(1.0f)
              +random(1.0f)+random(1.0f)+random(1.0f) )/6.0f; //Średnia 0.5
             //random(1.0); //Srednia taka sama, ale rozkład płaski
  }
  
  /// @brief Opis agenta.
  public String fullInfo(String fieldSeparator)
  {
    return "Immunity: "+immunity+fieldSeparator+
           "Flat at "+flatX+","+flatY+fieldSeparator+
           "Work at "+workX+","+workY+fieldSeparator+
           "Infected: "+infection;
  }
  
  /// @brief Czy agent jeszcze żyje?
  public boolean isAlive()
  {
    if(isSusceptible()) return true;
    return infection.state!=HostDeath;
  }
  
  /// @brief Czy agent jest podatny na infekcje?
  public boolean isSusceptible()
  {
    return infection==null;
  }
  
  /// @brief Czy agent jest zainfekowany?
  public boolean isInfected()
  {
    if(infection==null) return false;    assert infection.state!=HostDeath : "Nie można być martwym!";
    return infection.state!=Recovered && Infected<=infection.state; //<=
  }  
  
  // @brief Jakby zarażał od wyższego progu?
  //float   hasIllness() 
  //{
  //  if(infection==null) return 0;
  //  return infection.state; //???
  //}
  
  /// @brief Czy już wyzdrowiał?
  public boolean isRecovered()
  {
    if(infection==null) return false;
    return infection.state==Recovered;
  }
  
  /// @brief Czy jest umierający?
  public boolean justDying()
  {
    if(infection==null) 
        return false; // Nie ma na co umrzeć
        
    assert infection.state!=HostDeath : "Nie można umrzeć więcej niż raz!";
    
    if(infection.state==Recovered)
        return false;
        
    float prob=random(1); // Los na dany dzień
    
    if(prob<infection.pDeath) // Albo tego dnia umiera
    {
      infection.state=HostDeath;
      return true;
    }
    else return false; // Albo zyje dalej
  }
  
  /// @brief Właśnie wyleczony!
  public boolean justHealed()
  {
    assert !isSusceptible() : "Agent musi mieć zarazek!";
    assert !isRecovered()   : "Agent nie może być już wyleczony!";
    
    if(++(infection.state)==infection.duration)
    {
      infection.state=Recovered;
      return true;
    }
    else
      return false;
  }
  
  /// @brief Implementacja infekcji
  public void transferFrom(Agent infectious)
  {
    assert !infectious.isSusceptible() : "'infectious' musi mieć zarazek!";
    infection=infectious.infection.clone();
  }
 
}//_endOfClass

//*/////////////////////////////////////////////////////////////////////////////////////////
//  https://www.researchgate.net/profile/WOJCIECH_BORKOWSKI - ABM: AGENT from TEMPLATE
//*/////////////////////////////////////////////////////////////////////////////////////////
/// Agent needs to be initialised & they need logic of change
/// (Agent musi zostać zainicjowany i potrzebuje logiki zmian)
//*///////////////////////////////////////////////////////////

/// @brief Funkcja umieszcza agentów w domach i szuka im pracy
public void initializeAgents(Agent[][] agents,int[][] env)
{
   for(int a=0;a<agents.length;a++)     // po Y
    for(int b=0;b<agents[a].length;b++) // po X
      if(env[a][b]==Env_FLAT && random(1)<density) // Tylko w obszarach mieszkalnych
      {
        Agent curr=new Agent(b,a);
        liveCount++;
        
        // DODATKOWY KOD INICJALIZACJI AGENTÓW
        env[a][b]|=1; // Zaznaczamy mieszkanie jako zajęte
        
        // Kazdemu agentowi dajemy N szans znalezienia miejsca pracy
        for(int i=0;i<Nprob;i++)
        {
          curr.workX=PApplet.parseInt(random(agents[0].length));
          curr.workY=PApplet.parseInt(random(agents.length));
          if( env[curr.workY][curr.workX]/100==1    // Wszystkie miejsca pracy mają wartość w zakresie 100-199
          &&  (env[curr.workY][curr.workX] & 1) !=1 // Jak zajęte to ma na końcu jedynkę. Taka sztuczka   
          )
          {
                                               assert (env[curr.workY][curr.workX] & 1) == 0;
             env[curr.workY][curr.workX] |= 1; // Zaklepuje sobie to miejsce pracy
             break; // Mam już miejsce pracy
          }
          else // Nadal pracuje w domu
          {
            curr.workX=curr.flatX;
            curr.workY=curr.flatY;
          } 
        }
        agents[a][b]=curr;
      }
      
   // Inicjowanie infekcji z pozycji losowej
   int a=PApplet.parseInt(random(agents.length/3));
   int b=PApplet.parseInt(random(agents[0].length/3));
   if(agents[a][b]==null) // Gdyby go nie było
   {
      agents[a][b]=new Agent(b,a); // Konstruktor wymusza podanie x,y położenia!
      liveCount++;
   }
   println("Pacjent 0 @",b,"x",a);
   agents[a][b].infection=new Virus(defPDeath,defPSLeav,defDuration);
}

/// @brief Generuje protest o rozmiarze participationProb na głównej alei (oczywiście tylko z żywych agentów)
public void sheduleProtest(Agent[][] agents,int[][] env,float participationProb)
{        
   Agent curra; 
   for(int a=0;a<agents.length;a++)
    for(int b=0;b<agents[a].length;b++)
    {
     if( (curra=agents[a][b])!= null   // gdy agent jest żywy
     && curra.isAlive() 
     && participationProb>random(0,1)) // to może iść na protest
     {
       boolean OK=false;
       int na=a;
       int nb=agents[a].length/2;
       agents[a][b]=null; // znika z aktualnego miejsca
       do{                // print(na,nb,','); 
        if(agents[na][nb]==null
        && 
           env[na][nb]==Env_ROAD)
        {
          agents[na][nb]=curra;
          OK=true;
          println();
        }
        else
        {
          na+=random(1)<0.5f?-1:1;
          if(na<0) na=0;
          if(agents.length<=na) na=agents.length-1;
          
          nb+=random(1)<0.5f?-1:1;
          if(nb<0) nb=0;
          if(agents[na].length<=nb) nb=agents[na].length-1;
        }
       }while(!OK);
     }
    }
   println("PROTEST STARTED");
}

/// @brief Najprostrze przemieszczanie agentów sterowane upływem czasu symulacji
public void sheduleAgents(Agent[][] agents,int[][] env,int step)
{
   //lockdownness=0.20; // Ale lockdown nigdy nie jest kompletny (RACZEJ?)
   //lockdownstep=100;  // W którym kroku symulacji wprowadzamy lockdown
   float WP=(StepCounter<lockdownStep?dutifulness:lockdownness);
         
   Agent curra;                      //- println("Parzysty: ",step%2==0);
   for(int a=0;a<agents.length;a++)
    for(int b=0;b<agents[a].length;b++)
    {
     if( (curra=agents[a][b])!= null // Coś dalej do zrobienia gdy agent jest żywy
     && curra.isAlive()    )         // Tylko żywy może coś ze sobą zrobić np. do pracy
     {
       if(env[a][b]==Env_ROAD) // Jeśli jest na ulicy to wraca do domu!
       {
         agents[a][b]=null; // Z ulicy agent znika
         agents[curra.flatY][curra.flatX]=curra; // teleportuje się do domu
         continue;
       }
       
       if( curra.workX!=curra.flatX 
       && curra.workY!=curra.flatY)  // o ile nie pracuje w domu!!!
       {
         
         if(step % 2 == 0 ) // Jak 0 to z domu do pracy
         { 
           float workProbability=WP;
           if(curra.isInfected())
             workProbability*=1 - curra.infection.pSickLeave; //- println(workProbability);//DEBUG
  
           
           if(env[a][b]==Env_FLAT+1 // Tylko jak nadal jest w domu i zdecydował się iść
           && random(1)< workProbability
           )
           { 
             agents[a][b]=null; // A z domu znika
             agents[curra.workY][curra.workX]=curra; // Agent teleportuje się do pracy
           }
         }
         else // jak 1 to z pracy do domu
         {
           if(env[a][b]==Env_WORK+1) // Tylko jak nadal jest w pracy to z niej wraca
           { 
             agents[a][b]=null; // A z pracy znika
             agents[curra.flatY][curra.flatX]=curra; // Agent teleportuje się do domu
           }
         }
       }
     }
   } 
}

/// @brief Zmiany stanu agentów
public void  agentsChange(Agent[][] agents)
{
  // Zapamiętujemy stan przed krokiem
  int befInfected=sumInfected;
  int befRecovered=sumRecovered;
  int befDeath=sumDeath;
  
  // Zmiany...
  int MC=agents.length*agents[0].length;
  for(int i=0;i<MC;i++)
  {
    int a=(int)random(0,agents.length);    // `agents[a].lenght` na wypadek gdyby nam przyszło do głowy zrobić prostokąt
    int b=(int)random(0,agents[a].length); //- print(a,b,' ');
    
    if(agents[a][b]!= null )
    {
       // Jesli agent aktualny (centrum sąsiedztwa) zmarły lub zdrowy to nie zaraża wiec nic nie robimy
       if(!agents[a][b].isAlive() || agents[a][b].isSusceptible() || agents[a][b].isRecovered()) continue;
       
       // Wyliczenie lokalizacji sąsiadów
       int dw=(a+1) % agents.length;   
       int up=(agents.length+a-1) % agents.length;
       int right = (b+1) % agents[a].length;      
       int left  = (agents[a].length+b-1) % agents[a].length;

       if(agents[a][left]!=null
       && agents[a][left].isSusceptible() && random(1) < 1-agents[a][left].immunity )
         {agents[a][left].transferFrom(agents[a][b]); sumInfected++;}
        
       if(agents[a][right]!=null
       && agents[a][right].isSusceptible() && random(1) < 1-agents[a][right].immunity )
         {agents[a][right].transferFrom(agents[a][b]); sumInfected++;}
        
       if(agents[up][b]!=null
       && agents[up][b].isSusceptible() && random(1) < 1-agents[up][b].immunity )
         {agents[up][b].transferFrom(agents[a][b]); sumInfected++;}
        
       if(agents[dw][b]!=null
       && agents[dw][b].isSusceptible() && random(1) < 1-agents[dw][b].immunity ) 
         {agents[dw][b].transferFrom(agents[a][b]); sumInfected++;}
       
       if(agents[a][b].justDying()) // Albo tego dnia umiera
        { 
          sumDeath++;liveCount--;
          //agents[a][b]=null;        // Można by dawać mu stan "dead", ale...
          //agents[a][b].state=Death; // Ale to trzeba uwzglednić przy statystyce!
        }
        else
        {
          // Albo jest wyleczony
          if(agents[a][b].justHealed())
          {
              sumRecovered++;
          }
          //else //ALBO NADAL CIERPI!
        }
    }
  }
  // Zapamiętujemy zmiane w podstawowych statystykach jaka się dokonała w kroku symulacji
  deaths.append(sumDeath-befDeath);
  newcas.append(sumInfected-befInfected);
  cured.append(sumRecovered-befRecovered);
}

//*//////////////////////////////////////////////////////////////////////////////////////////////////////////
//  https://www.researchgate.net/profile/WOJCIECH_BORKOWSKI - ABM: BASIC INITIALISATION & EVERY STEP CHANGE
//*//////////////////////////////////////////////////////////////////////////////////////////////////////////
/// Germs, i.e. various "little things" that can harm agents.
/// (Zarazki czyli różne "żyjątka", które mogę szkodzić agentom)
//*////////////////////////////////////////////////////////////

/// @brief Klasa bazowa wszelkich "żyjątek"
class Animalcule
{
}//_endOfClass

/// @brief Klasa bazowa zarazków.
class Germ extends Animalcule
{          
  float  pDeath=0.0f;      //!< Średnie prawdopodobieństwo śmierci w danym kroku(!) choroby. Teraz krok to 12 godzin.
  float  pSickLeave=0.09f; //!< Prawdopodobieństwo, że danego DNIA chory agent nie będzie w stanie iść do pracy.   
  int    duration=14;     //!< Czas trwania infekcji (w krokach symulacji). Teraz krok to 12 godzin!!! Czyli default to 7 dni.
                          //!< W modelu profesjonalnym czas powinien być raczej w godzinach.
                         
  /// @brief Czy zarazek już zabił żywiciela?                        
  public boolean hostIsDead() { return false;} //!< Domyślnie nigdy nie umiera bo to KATAR.
  
  /// @brief Opis danego zarazka.
  public String fullInfo(String fieldSeparator)
  {
    return "pDeath: "+pDeath+fieldSeparator+
           "pSickLeave: "+pSickLeave+fieldSeparator+
           "duration: "+pDeath+fieldSeparator;
  }
}//_endOfClass

/// @brief Klasa bazowa wszelkich wirusów.
class Virus extends Germ
{
  float state; //!< "Miano" wirusów/stadium infekcji.
  
  /// @brief Konstruktor wirusa. Na razie wciąż ten bardzo uproszczony model.
  Virus(float iPDeath,float iPSickLeave,int iDuration)
  {
    pDeath=iPDeath;
    pSickLeave=iPSickLeave;
    duration=iDuration;
    state=1; //Stan początkowy - iniekcja wirusa
  }
  
  /// @brief Nowy wirus do zaatakowanie innego agenta. Mogłby ulec jakimś mutacjom.
  public Virus clone()
  {
    return new Virus(pDeath,pSickLeave,duration);
  }
  
  /// @brief Czy już przekroczono miano krytyczne wirusa, które zabija żywiciela?
  public boolean hostIsDead() 
  { 
    return state>=HostDeath;
  }
  
  /// @brief Informacja o zarazku
  public String fullInfo(String fieldSeparator)
  {
    return super.fullInfo(fieldSeparator)+"State: "+state+fieldSeparator;
  }
}//_endOfClass

//*/////////////////////////////////////////////////////////////////////////////////////////
//  https://www.researchgate.net/profile/WOJCIECH_BORKOWSKI - City of Plague
//*/////////////////////////////////////////////////////////////////////////////////////////
/// World is a one of two central class of each ABM model
/// (Świat jest jedną z dwóch klas centralnych każdego modelu ABM)
//*///////////////////////////////////////////////////////////////
int StepCounter=0;     ///< GLOBALNY LICZNIK KROKÓW SYMULACJI.

/// @brief Klasa świata symulacji. Łączy wszystkie niezbędne składowe modelu.
class World
{
  Agent agents[][]; //!< DWUWYMIAROWA TABLICA AGENTÓW.
  int      env[][]; //!< TABLICA SRODOWISKA - "environment".
  
  /// KONSTRUKTOR ŚWIATA
  World(int side)
  {
    env=new int[side][2*side];
    agents=new Agent[side][2*side];
  }
}//_endOfClass

// BARDZIEJ ZŁOŻONE FUNKCJONALNOŚCI ZOSTAŁY ZDEFINIOWANE JAKO OSOBNE FUNKCJE
// A NIE METODY KLASY World ZE WZGLĘDU NA OGRANICZENIA SKŁADNI PROCESSINGU
// NIE POZWALAJĄCEJ SCHOWAĆ GDZIEŚ INDZIEJ MNIEJ ISTOTNYCH METOD KLASY
//*/////////////////////////////////////////////////////////////////////////

/// @brief Inicjalizacja całości świata.
public void initializeModel(World world)
{
  initializeEnv(world.env);
  initializeAgents(world.agents,world.env);
}

/// @brief Wizualizacja całości świata.
public void visualizeModel(World world)
{
  visualizeEnv(world.env);
  visualizeAgents(world.agents);
}

/// @brief Krok symulacji.
public void modelStep(World world)
{
   //environmentChange(world.env); // W tej symulacji niepotrzebne
   agentsChange(world.agents);
   if(protestStep==StepCounter)
   {
       sheduleProtest(world.agents,world.env,0.1f);
       visualizeModel(TheWorld); // DLA PEWNOŚCI, ŻEBY PROTEST ZAWSZE BYŁ WIDOCZNY CHOCIAŻ NA FILMIE
       NextVideoFrame();         // FUNKCJA ZAPISU KLATKI FILMU. 
   }
   else
       sheduleAgents(world.agents,world.env,StepCounter);
   StepCounter++;
}

//*////////////////////////////////////////////////////////////////////////////////////////////////
//  https://www.researchgate.net/profile/WOJCIECH_BORKOWSKI - ABM: WORLD OF AGENTS from template
//*////////////////////////////////////////////////////////////////////////////////////////////////
/// "environment", i.e. a map of the agents' living environment
/// (... czyli mapa środowiska życia agentów)
//*////////////////////////////////////////////////////////////

//enum EnvTile {FLAT=0,WORK,ROAD,REST} //Takie enum w Processingu jest obiektem co jest w tej symulacji bez sensu!

// Environment "tiles"
final int Env_FLAT=0;      ///< Komórka pusta.
final int Env_WORK=100;    ///< Strefa pracy.
final int Env_SHOP=120;    ///< Strefa zakupów.
final int Env_ROAD=200;    ///< droga.
final int Env_REST=300;    ///< Strefa rekracji.

float limit=105;           ///< ???
float fcars=0.05f;          ///< Jaką część szerokości pasa zabudowy zajmuje jego ulica.
int   streetcount=0;       ///< zliczanie ulic podczas inicjalizacji. To są te poziome.
int   avenuecount=0;       ///< zliczanie alei podczas inicjalizacji. Aleje są to te pionowe!

/// @brief Inicjalizacja środowiska.
public void initializeEnv(int[][] env)
{
  limit=10;
  sierpinskiCarpetRect(env,Env_WORK,0,0,env[0].length,env.length);
  limit=1;
  street(env,0,env.length);    // Ulice są poziome
  avenue(env,0,env[0].length); // Aleje są pionowe
  //println(streetcount,avenuecount);
}

/// @brief Wypełnianie bloku środowiska.
public void fillblock(int[][] env,int val,int x1,int y1,int x2,int y2)
{
  for(int a=x1;a<x2;a++)
   for(int b=y1;b<y2;b++)
     env[b][a]=val;
}

/// @brief Rysowanie alei (pionowo).
public void avenue(int[][] env,float start,float end)
{
  float len=end-start; //Szerokość pasa zabudowy
  float weight=len*fcars; //Szerokość alei
  if(weight<limit) return; //Czy nie za wąska dla samochodu?
  avenuecount++; //Zliczenie
  
  float center=(start+end)/2;
  
  fillblock(env,Env_ROAD,round(center-weight/2),0,round(center+weight/2),env.length); //Aleje są pionowe
  
  avenue(env,start,center-weight/2);
  avenue(env,center+weight/2,end);
}

/// @brief Rysowanie ulicy (poziomo).
public void street(int[][] env,float start,float end)
{
  float len=end-start;     // Szerokość pasa zabudowy
  float weight=len*fcars;  // Szerokość ulicy
  if(weight<limit) return; // Czy nie za wąska dla samochodu?
  streetcount++;           // Zliczenie
  
  float center=(start+end)/2;
  
  fillblock(env,Env_ROAD,0,round(center-weight/2),env[0].length,round(center+weight/2)); //Ulice są poziome
  
  street(env,start,center-weight/2);
  street(env,center+weight/2,end);
}

/// @brief Wypełnianie środowiska ulicami.
public void sierpinskiCarpetRect(int[][] env,int val,int x, int y, int sizex, int sizey)
{
   if (sizey < limit)
      return; // println(sizex,sizey);
   
   sizex = sizex / 3; 
   sizey = sizey / 3; 
   
   fillblock(env,val,x+sizex, y+sizey, x+2*sizex, y+2*sizey);//Wycięcie

   //Wywołania rekurencyjne dla 8 kwadratowych sąsiedztw
   //Po rogach
   sierpinskiCarpetRect(env,val,x        ,        y,sizex,sizey);
   sierpinskiCarpetRect(env,val,x+2*sizex,y+2*sizey,sizex,sizey);
   sierpinskiCarpetRect(env,val,x        ,y+2*sizey,sizex,sizey);
   sierpinskiCarpetRect(env,val,x+2*sizex,y        ,sizex,sizey);
   //Po bokach
   sierpinskiCarpetRect(env,val,x        ,y+sizey  ,sizex,sizey);
   sierpinskiCarpetRect(env,val,x+sizex  ,y        ,sizex,sizey);
   sierpinskiCarpetRect(env,val,x+2*sizex,y+sizey  ,sizex,sizey);
   sierpinskiCarpetRect(env,val,x+sizex  ,y+2*sizey,sizex,sizey);
}

//*/////////////////////////////////////////////////////////////////////////////////////////
//  https://www.researchgate.net/profile/WOJCIECH_BORKOWSKI - City of Plague
//*/////////////////////////////////////////////////////////////////////////////////////////
/// A very simple histogram of agents by one property.
/// (Bardzo prosty histogram agentów wg jednej właściwości)
//*/////////////////////////////////////////////////////////
int Max=0;           ///< Max wspólny dla całej symulacji.

/// @brief Tablica frekwencji odporności wraz z rysowaniem.
/// @details
///   Funkcja przechodzi po wszystkich agentach i zlicza wg. klas odpornosci.
///   Potem rysuje w zadanym miejscu histogram o maksymalnej wysokości 'hight'.
public void histogram(Agent[][] agents,float startx,float starty,float hight)
{
  int NumOfBaskets=100;
  int Basket[]=new int[NumOfBaskets+1];
  int N=0;     //Licznik żywych
  //int Max=0; // Albo Max resetowany dla każdego kroku
  Agent curra; // Pomocniczy uchwyt agenta
  
  // Zliczanie 
  for(int a=0;a<agents.length;a++)
   for(int b=0;b<agents[a].length;b++)
   {
    // ZLICZANIE AGENTA
    if( (curra=agents[a][b]) != null 
        && curra.isAlive() // Nie doliczamy zmarłych do tej statystyki
    )
    {
      N++;//Żywy
      int cl=round(curra.immunity*NumOfBaskets); // Z odporniością w klasie "cl"?
      Basket[cl]++;                              // Doliczamy go.
      if(Basket[cl]>Max) Max=Basket[cl];         // Sprawdzamy czy nie urosło "Max".
    }
   }
   
   // Rysowanie
   stroke(random(255),random(255),random(255));
   for(int i=0;i<=NumOfBaskets;i++)
   {
     float val=Basket[i];
     val/=Max;val*=hight;
     //map(val,0,Max,0,hight);
     line(startx+i,starty,startx+i,starty-val);
   }
   
   // Opis
   fill(random(255),random(255),random(255));
   text("N:"+N+"\nMax:"+Max,startx+NumOfBaskets,starty);
}

//*/////////////////////////////////////////////////////////////////////////////////////////
//  https://www.researchgate.net/profile/WOJCIECH_BORKOWSKI - City of Plague
//*/////////////////////////////////////////////////////////////////////////////////////////
/// Graph of changes over time
/// (Wykres zmian w czasie)
//*/////////////////////////////

/// @brief Funkcja rysuje przebieg jednej zmiennej.
/// \param height - to maksymalna wysokość wykresu.
/// \param logarithm - oznacza że dane zostaną zlogarytmowane.
public void timeline(FloatList data, float startX, float startY, float height,boolean logarithm)
{
  float   max=-Float.MAX_VALUE; // Wartość maksimum.
  int     whmax=-1;             // Gdzie jest maksimum?
  float   min=Float.MAX_VALUE;  // Wartość minimum.
  int     whmin=-1;             // Gdzie jest minimum?
  int     N=data.size();        // Ile pomiarów?
  float  lenght=width-startX;   // Ile miejsca na wykres?
  
  // Szukanie minimum i maksimum
  for(int t=0;t<N;t++)
  {
    float val=data.get(t);
    if(Float.isNaN(val)) continue; // Pomija nie liczby 
    if(val>max) { max=val; whmax=t;}
    if(val<min) { min=val; whmin=t;}
  }
  
  if(logarithm)
  {
    max=(float)Math.log10(max+1); // +1 to takie oszustwo 
    min=(float)Math.log10(min+1); // żeby 0 nie wywalało obliczeń
  }
  
  if(min==max) max++;
  
  // Właściwe rysowanie
  float wid=lenght/N;             //- println(width,N,wid,min,max);
  float oldy=-Float.MIN_VALUE;
  for(int t=0;t<N;t++)
  {
    float val=data.get(t);
    
    if(Float.isNaN(val)) continue; // Pomija nie liczby! 
    
    if(logarithm)
      val=map((float)Math.log10(val+1),min,max,0,height);    
    else 
      val=map(val,min,max,0,height);
    
    float x=t*wid;
    if(oldy!=-Float.MIN_VALUE)
    {
      line (startX+x-wid,startY-oldy,startX+x,startY-val); //- println(wid,x-wid,oldy,x,val);
    }
    else
      point(startX+x,startY-val);                          //- println(startX+x,startY-val);
    
    oldy=val;
    
    if(t==whmax || t==whmin)
    {
      textAlign(LEFT,BOTTOM);
      String out=""+data.get(t);
      text(out,startX,startY-val);   // Na osi X
      text(out,startX+x,startY-val); // Przy danych
    }
  }
}

/// @brief Gdy trzeba narysować historię kilku zmiennych.
/// @details To jest wersją bardzo prymitywną, ale działa :-D
/// @note!:  wspólna skala!!!
public void timeline(FloatList data_a, FloatList data_b, FloatList data_c,float startX, float startY, float height,boolean logarithm,int color_a,int color_b,int color_c)
{
  float   max=-Float.MAX_VALUE;  // Tu będzie prawdziwa wartość
  float   gmax=0;                // A tu przeliczona dla grafiki
  float   min=Float.MAX_VALUE;   // J.w.
  float   gmin=0;                // Analogicznie j.w.
  int     N1=data_a.size(),N2=data_b.size(),N3=data_c.size(); //Ile pomiarów?
  float   lenght=width-startX;   // Ile miejsca na wykres?
  
  // Szukanie minimum i maksimum
  for(int t=0;t<N1;t++)
  {
    float val=data_a.get(t);
    if(Float.isNaN(val)) continue; // Pomija nie liczby 
    if(val>max) max=val;
    if(val<min) min=val;
  }
  
  for(int t=0;t<N2;t++)
  {
    float val=data_b.get(t);
    if(Float.isNaN(val)) continue; // Pomija nie liczby 
    if(val>max) max=val;
    if(val<min) min=val;
  }
  
  for(int t=0;t<N3;t++)
  {
    float val=data_c.get(t);
    if(Float.isNaN(val)) continue; // Pomija nie liczby 
    if(val>max) max=val; 
    if(val<min) min=val;
  }
  
  if(logarithm)
  {
    gmax=(float)Math.log10(max+1); // +1 to takie oszustwo 
    gmin=(float)Math.log10(min+1); // żeby 0 nie wywalało obliczeń
  }
  else
  {
    gmax=max;
    gmin=min;
  }
  
  if(gmin==gmax) gmax++;
  
  // Właściwe rysowanie
  float wid=lenght/max(N1,N2,N3);  // Najdłuższy decyduje
  float oldy=-Float.MIN_VALUE;
  stroke(color_a);//fill(color_a);
  for(int t=0;t<N1;t++)
  {
    float val=data_a.get(t);
    if(Float.isNaN(val)) continue; // Pomija nie liczby 
    
    if(logarithm)
      val=map((float)Math.log10(val+1),gmin,gmax,0,height);    
    else 
      val=map(val,gmin,gmax,0,height);
    
    float x=t*wid;
    if(oldy!=-Float.MIN_VALUE)
      line (startX+x-wid,startY-oldy,startX+x,startY-val);
    else
      point(startX+x,startY-val);
    
    oldy=val;
  }

  oldy=-Float.MIN_VALUE;
  stroke(color_b); //fill(color_b);
  for(int t=0;t<N2;t++)
  {
    float val=data_b.get(t);
    if(Float.isNaN(val)) continue; // Pomija nie liczby 
    
    if(logarithm)
      val=map((float)Math.log10(val+1),gmin,gmax,0,height);    
    else 
      val=map(val,gmin,gmax,0,height);
    
    float x=t*wid;
    if(oldy!=-Float.MIN_VALUE)
      dottedLine(startX+x-wid,startY-oldy,startX+x,startY-val,2);
    else
      point(startX+x,startY-val);
    
    oldy=val;
  }
  
  oldy=-Float.MIN_VALUE;
  stroke(color_c); //- fill(color_c);
  for(int t=0;t<N3;t++)
  {
    float val=data_c.get(t);
    if(Float.isNaN(val)) continue; // Pomija nie liczby 
    
    if(logarithm)
      val=map((float)Math.log10(val+1),gmin,gmax,0,height);    
    else 
      val=map(val,gmin,gmax,0,height);
    
    float x=t*wid;
    if(oldy!=-Float.MIN_VALUE)
      dottedLine(startX+x-wid,startY-oldy,startX+x,startY-val,3);
    else
      point(startX+x,startY-val);
    
    oldy=val;
  }
  
  // Min i max są wspólne.
  textAlign(LEFT,BOTTOM);
  text(""+max,startX,startY-height); // Na osi X
  text(""+min,startX,startY);        // Na osi X
}

/// @brief Rysowanie linii kropkowanej.
/// @note  wg.: https://processing.org/discourse/beta/num_1219255354.html
public void dottedLine(float x1, float y1, float x2, float y2, float steps)
{
 for(int i=0; i<=steps; i++) {
   float x = lerp(x1, x2, i/steps); // funkcja `lerp()` jest bardzo użyteczna :-)
   float y = lerp(y1, y2, i/steps);
   //noStroke();ellipse(x, y,2,2);  // Używanie elipsy zamiast punktu nie jest zbyt wydajne ;-)
   point(x,y);
 }
}

//*/////////////////////////////////////////////////////////////////////////////////////////
//  https://www.researchgate.net/profile/WOJCIECH_BORKOWSKI - City of Plague
//*/////////////////////////////////////////////////////////////////////////////////////////
/// Any simulation have to collect and write down statistics from [every] step
/// (Każda symulacja wymaga gromadzenia i zapisywania statystyk z [każdego] kroku)
//*/////////////////////////////////////////////////////////////////////////////////////
PrintWriter outstat;

/// @brief Przygotowanie do zapisu statystyk.
/// @details Otwarcie pliku logu i zapis nagłówka zmiennych.
public void initializeStats()
{
  String FileName=modelName+="_"+year()+'.'+nf(month(),2)+'.'+nf(day(),2)+'.'+nf(hour(),2)+'.'+nf(minute(),2)+'.'+nf(second(),2)+'.'+millis();
  outstat=createWriter(FileName+".out");
  outstat.println( "ST:\tStepCounter\tliveCount"
                   +"\tZ\tsumInfected\tnewcases"
                   +"\tW\tsumRecovered\tcured"
                   +"\tU\tsumDeath\tdeaths"
                   +"\t");
}

/// @brief Obliczanie i zapis statystyk.
/// @note  Do wywołania w `draw()`
public void doStatistics(World world)
{
  doStatisticsOnAgents(world.agents); // W tej symulacji tylko dla agentów bo środowisko się nie zmienia.
}

/// @brief Obliczanie statystyk dla agentów i ich zapis.
/// @details Większość statystyk jest obliczana w trakcie kroku symulacji,
///          ale tu są zapisywane, razem z tym co wyliczono po kroku.
/// @note Każdy krok w jednym wierszu.
public void doStatisticsOnAgents(Agent[][] agents)
{  
  Agent curra;
  liveCount=0;
  
  for(int a=0;a<agents.length;a++)
   for(int b=0;b<agents[a].length;b++)
    if( (curra=agents[a][b]) != null )
    {     
      //...ANY CALCULATIONS MORE?
      //...
      liveCount++;
    }
  
   if(outstat!=null)
      outstat.println(  "ST:\t"+StepCounter+"\t"+liveCount
                      + "\tZ\t"+sumInfected+"\t"+(newcas.size()>1?newcas.get(newcas.size()-1):0)
                      + "\tW\t"+sumRecovered+"\t"+(cured.size()>1?cured.get(cured.size()-1):0)
                      + "\tU\t"+sumDeath+"\t"+(deaths.size()>1?deaths.get(deaths.size()-1):0)
                      + "\t");
   
   //outstat should be closed in exit() --> see Exit.pde
}

//*////////////////////////////////////////////////////////////////////////////////////////////////
//  https://www.researchgate.net/profile/WOJCIECH_BORKOWSKI - ABM: STATISTICS LOG from TEMPLATE
//*////////////////////////////////////////////////////////////////////////////////////////////////
/// World full of agents need method of visualisation on screen/window
/// (Świat pełen agentów potrzebuje metody wizualizacji na ekranie/w oknie)
//*/////////////////////////////////////////////////////////////////////////

/// @brief Wizualizacja środowiska
public void visualizeEnv(int[][] env)
{
  noStroke(); // Nie ma powodu być wewnątrz pętli!
  for(int a=0;a<env.length;a++)
   for(int b=0;b<env[a].length;b++)
   {
    //KOLORYZACJA ŚRODOWISKA 
    switch(env[a][b]){
    case Env_FLAT:fill(255);break;
    case Env_FLAT+1:fill(220);break; // Zajęte mieszkanie
    case Env_WORK:fill(128);break;
    case Env_WORK+1:fill(64);break;  // Zajęte miejsca pracy 
    case Env_ROAD:fill(0,0,48);break;
    case Env_REST:fill(0,128,0);break;  
    default:fill(255,0,0);break;
    }
    
    rect(b*cwidth,a*cwidth,cwidth,cwidth); // WŁAŚCIWE RYSOWANIE KOMÓRKI
   }
}

/// @brief Wizualizacja agentów.
public void visualizeAgents(Agent[][] agents)
{
  noStroke(); // Nie ma powodu być w pętli!
  ellipseMode(CORNER);
  Agent curra;
  for(int a=0;a<agents.length;a++)
   for(int b=0;b<agents[a].length;b++)
   {
    // KOLORYZACJA AGENTA
    if( (curra=agents[a][b]) != null )
    {
      float green=curra.immunity*200;
      if(curra.isSusceptible())
      {
        fill(0,green,128);
      }
      else
        switch(PApplet.parseInt(curra.infection.state))
        { 
        case Recovered:  fill(0,128,0);break;   // Już przeszedł chorobę. Wyleczony!
        case Infected:   fill(0,255,255);break; // Właśnie zachorował
        case HostDeath:  fill(255,0,0);break;   // Zmarły
        default:         fill(random(255),green,random(255)); // Chory
        break;
        } 
      
      rect(b*cwidth,a*cwidth,cwidth,cwidth); //WŁAŚCIWE RYSOWANIE 
    }    
   }
}

//*//////////////////////////////////////////////////////////////////////////////////////////////////////
//  https://www.researchgate.net/profile/WOJCIECH_BORKOWSKI - ABM city_of_plague: VISUALISATION
//*//////////////////////////////////////////////////////////////////////////////////////////////////////
/// Event handling tailored to this model.
/// (Dopasowana do modelu obsługa zdarzeń)
//*///////////////////////////////////////
 
//double minDist2Selec=MAX_INT;
//double maxTransSelec=-MAX_INT;

public void keyPressed() 
{
  println("RECIVED:'",key,"\' CODE:",PApplet.parseInt(key)); 
  switch(key)
  {
  case '1': STEPSperVIS=1;text("StPerV: "+STEPSperVIS,1,16);/*DeltaMC=1;*/StepCounter=PApplet.parseInt(StepCounter);break;
  case '2': STEPSperVIS=2;text("StPerV: "+STEPSperVIS,1,16);StepCounter=PApplet.parseInt(StepCounter);break;
  case '3': STEPSperVIS=5;text("StPerV: "+STEPSperVIS,1,16);StepCounter=PApplet.parseInt(StepCounter);break;
  case '4': STEPSperVIS=10;text("StPerV: "+STEPSperVIS,1,16);StepCounter=PApplet.parseInt(StepCounter);break;
  case '5': STEPSperVIS=25;text("StPerV: "+STEPSperVIS,1,16);StepCounter=PApplet.parseInt(StepCounter);break;
  case '6': STEPSperVIS=50;text("StPerV: "+STEPSperVIS,1,16);StepCounter=PApplet.parseInt(StepCounter);break;
  case '7': STEPSperVIS=100;text("StPerV: "+STEPSperVIS,1,16);StepCounter=PApplet.parseInt(StepCounter);break;
  case '8': STEPSperVIS=150;text("StPerV: "+STEPSperVIS,1,16);StepCounter=PApplet.parseInt(StepCounter);break;
  case '9': STEPSperVIS=200;text("StPerV: "+STEPSperVIS,1,16);StepCounter=PApplet.parseInt(StepCounter);break;
//  case '0': STEPSperVIS=1;DeltaMC=0.2;text("DeltaMC: "+DeltaMC,1,16);break;
  case ' ': save(modelName+"."+nf((float)StepCounter,6,5)+".PNG");
            //write(world,modelName+"."+nf((float)StepCounter,6,5));//Aktualny stan ekosystemu
            break;
  case ESC: simulationRun=!simulationRun; break;
  case 's': simulationRun=false; break;
  case 'r': simulationRun=true; break;
  default:println("Command '"+key+"' unknown");
          println("USE:");
          println("1-9 for less frequent visualisation");
          println("  0 for most frequent visualisation");
          println("ESC,r,s for pause/run simulation");
          println("SPACE for dump the current screen\n"); 
  break;
  }
  
  if (key == ESC) 
  {
    key = 0;  // Fools! don't let them escape!
  }
}


//*/////////////////////////////////////////////////////////////////////////////////////////
//  https://www.researchgate.net/profile/WOJCIECH_BORKOWSKI - ABM EVENTS TEMPLATE
//*/////////////////////////////////////////////////////////////////////////////////////////
// When exit?
//*//////////

/// @brief Exit function is called whenever a window is closed.
public void exit()          
{
  noLoop();          // For to be sure...
  delay(100);        // it is possible to close window when draw() is still working!
  //write(world,modelName+"."+nf((float)StepCounter,5,5));//end state of the system
  
  if(outstat!=null)
  {
    outstat.flush();  // Writes the remaining data to the file
    outstat.close();  // Finishes the file
  }
  
  if(WITH_VIDEO) CloseVideo();    // Finalise of Video export
  
  println(modelName,"said: Thank You!");
  super.exit();       // Do, what library superclass have to do at `exit()`!
} 

//*/////////////////////////////////////////////////////////////////////////////////////////
//  https://www.researchgate.net/profile/WOJCIECH_BORKOWSKI - EXIT TEMPLATE
//*/////////////////////////////////////////////////////////////////////////////////////////
/// Support for object search on mouse click
/// (Obsługa wyszukiwania obiektu po kliknięciu myszy)
//*///////////////////////////////////////////////////

int searchedX=-1;         ///< Pozycja X punktu szukanego.
int searchedY=-1;         ///< Pozycja Y punktu szukanego.
boolean Clicked=false;    ///< Czy było też kliknięcie.

int selectedX=-1;         ///< Pozycja X szukanego agenta.
int selectedY=-1;         ///< Pozycja Y szukanego agenta.
Agent selected=null;      ///< Szukany agent, o ile znaleziono.

//double minDist2Selec=MAX_INT;  ///< ???
//double maxTransSelec=-MAX_INT; ///< ???

/// @brief Simple version of Pair class. 
/// @details For returning a pair of Int from a function
class PairOfInt
{
    public final int a;
    public final int b;

    public PairOfInt(int a,int b) 
    {
        this.a = a;
        this.b = b;
    }
}//_endOfClass

/// @brief Obsługa kliknięcia myszy.
/// @detail Szuka odpowiadającej komórki i agenta i wyświetla informacje o nich.
public void mouseClicked()
{
  //println("Mouse clicked at ",mouseX,mouseY); //DEBUG
  //Clicked=true; //To nie jest używane (na razie?)
  searchedX=mouseX;
  searchedY=mouseY; 
  
  PairOfInt result=findCell(TheWorld.agents); // But 1D searching is belong to you!
  if(result!=null) // Znaleziono
  {
    selectedX=result.a;
    selectedY=result.b;
    if((selected=TheWorld.agents[selectedY][selectedX])!=null)
    {
      println("Cell",selectedX,selectedY,"belong to",selected);
      println("Env. value:",TheWorld.env[selectedY][selectedX]);
      println("\t"+selected.fullInfo(";\n\t"));
      if(selected.infection!=null)
          println("\t\t"+selected.infection.fullInfo(";\n\t\t"));  
    }
    else
    {
      println("Cell",selectedX,selectedY,"is empty");
      println("Env. value:",TheWorld.env[selectedY][selectedX]);
    }
  }
}

/// @brief Poszukiwanie komórki która jest wizualizowana w danym punkcie okna.
/// @details Używamy globalnych zmiennych `mouseX` i `mouseY` dla szybkości.
public PairOfInt findCell(Agent[][] agents)
{ // @internal Przeliczanie współrzędnych myszy na współrzędne komórki 
  //           Parametr jest tylko do sprawdzenie typu i ROZMIARÓW
  // @note  Działa o tyle o ile wizualizacja komórek startuje w punkcie `0,0` !!!
  int x=mouseX/cwidth;
  int y=mouseY/cwidth;
  if(0<=y && y<agents.length
  && 0<=x && x<agents[y].length)
      return new PairOfInt(x,y);
  else
      return null;
}


//*/////////////////////////////////////////////////////////////////////////////////////////
//  https://www.researchgate.net/profile/WOJCIECH_BORKOWSKI - ABM EVENTS FROM TEMPLATE
//*/////////////////////////////////////////////////////////////////////////////////////////
/// Module for recording video from the simulation.
/// (Moduł do zapisu wideo z symulacji.) 
//*////////////////////////////////////////////////////
// To musi być w `setup()` żeby było zapisane video:
//
//  initVideoExport(this,FileName,int Frames)); // Klasa VideoExport musi mieć dostep do obiektu aplikacji Processingu
//                                              // Najlepiej wywołać na końcu `setup()`. Okno musi mieć PARZYSTE rozmiary
//  
// a to dla każdej klatki
//
//  NextVideoFrame(); // Video frame
//
//na koniec zaś:
//
//  CloseVideo()
//
 // Oraz importujemy niezbędną biblioteką zawierającą klasę VideoExport

VideoExport videoExport; // KLASA z biblioteki "VideoExport" Abe Pazosa - trzeba zainstalować
                         // "http://funprogramming.org/VideoExport-for-Processing/examples/basic/basic.pde"
                         // Oraz zainstalować program "ffmpeg" żeby działało.
int videoFramesFreq=0;           

public void initVideoExport(processing.core.PApplet parent, String Name,int Frames)
{
  videoFramesFreq=Frames;
  videoExport = new VideoExport(parent,Name); // Klasa VideoExport musi mieć dostep do obiektu aplikacji Processingu
  videoExport.setFrameRate(Frames);           // Nie za szybko!
  videoExport.startMovie();
  text(Name,1,20);
  videoExportEnabled=true;
}
                        
public void FirstVideoFrame()
{
  if(videoExportEnabled)
  {  
     fill(0,128,255);textAlign(LEFT,BOTTOM);
     text("2020 (c) W.Borkowski @ ISS University of Warsaw",1,height); 
     //text(videoExport.VERSION,width/2,height);
     delay(200);
     for(int i=0;i<videoFramesFreq;i++) // Musi trwać sekundę czy coś...
       videoExport.saveFrame();         // Video frame
  }
}

public void NextVideoFrame()
{  
   if(videoExportEnabled)
     videoExport.saveFrame(); // Video frame
}
                     
public void CloseVideo() ///< To wołamy gdy chcemy zamknąć.
{
  if(videoExport!=null)
  { 
   fill(0);textAlign(LEFT,BOTTOM);
   // powinno być jakieś "force screen update", ale nie znalazłem
   for(int i=0;i<videoFramesFreq;i++) // Musi trwać sekundę czy coś...
   {
       fill(random(255),random(255),random(255));
       text("2020 (c) W.Borkowski @ Institute for Social Studies, University of Warsaw",1,height);
       videoExport.saveFrame(); //Video frame
       print("*"); //DEBUG
   }
   videoExport.saveFrame();  // Video frame - LAST
   videoExport.endMovie();   // Koniec filma
   videoExportEnabled=false;
   videoExport=null;
  }
}

static boolean     videoExportEnabled=false; ///< init will set up it for true

//*/////////////////////////////////////////////////////////////////////////////////////////
//  https://www.researchgate.net/profile/WOJCIECH_BORKOWSKI - MOVIE MAKER 
//*/////////////////////////////////////////////////////////////////////////////////////////
  public void settings() {  size(1200,750);  noSmooth();  pixelDensity(1); }
  static public void main(String[] passedArgs) {
    String[] appletArgs = new String[] { "cityOfplague" };
    if (passedArgs != null) {
      PApplet.main(concat(appletArgs, passedArgs));
    } else {
      PApplet.main(appletArgs);
    }
  }
}
